In [26]:
library(dplyr)
library(car)

Loading required package: carData


Attaching package: ‘car’


The following object is masked from ‘package:dplyr’:

    recode

In [20]:
dataset_url <- "https://raw.githubusercontent.com/wilkmzhou/STAT306_PROJECT_REPORT_2026/refs/heads/main/mercedes_benz_listings_cleaned.csv"

benzData <- read.csv(dataset_url)
head(benzData, n = 3)

  Vehicle_Name                         Year Vehicle_Age Model_Series Trim_Level
1 2025 Mercedes-Benz AMG S 63 E 4MATIC 2025 1           AMG S 63     S 63
2 2025 Mercedes-Benz GLE 580 4MATIC    2025 1           GLE          E 580
3 2025 Mercedes-Benz GLS 450 4MATIC    2025 1           GLS          S 450
  Body_Type Is_AMG Is_4MATIC Mileage_Miles Mileage_Category Price_USD
1 Other     1      1          9860         Low (< 20K)      151900
2 SUV       0      1          3154         Low (< 20K)       82975
3 SUV       0      1         15496         Low (< 20K)       75500
  Price_Category  Price_Per_Mile
1 Luxury (> $70K) 15.405680
2 Luxury (> $70K) 26.307863
3 Luxury (> $70K)  4.872225

In [21]:
benzData <- benzData |>
    na.omit() |>
    select(-Price_Per_Mile, -Price_Category, -Year, -Mileage_Category, -Is_AMG, -Vehicle_Name)
head(benzData, n = 3)

  Vehicle_Age Model_Series Trim_Level Body_Type Is_4MATIC Mileage_Miles
1 1           AMG S 63     S 63       Other     1          9860
2 1           GLE          E 580      SUV       1          3154
3 1           GLS          S 450      SUV       1         15496
  Price_USD
1 151900
2  82975
3  75500

In [23]:
benzFit1 <- lm(Price_USD ~ ., data = benzData)
summary(benzFit1)

Call:
lm(formula = Price_USD ~ ., data = benzData)

Residuals:
   Min     1Q Median     3Q    Max
-18628  -2449      0   2502  18628

Coefficients: (22 not defined because of singularities)
                              Estimate Std. Error t value Pr(>|t|)
(Intercept)                  3.926e+04  5.869e+03   6.689 7.90e-09 ***
Vehicle_Age                 -1.667e+03  5.400e+02  -3.088 0.003035 **
Model_SeriesAMG A 35         1.506e+04  8.557e+03   1.760 0.083416 .
Model_SeriesAMG E 53         3.205e+04  8.522e+03   3.760 0.000383 ***
Model_SeriesAMG G 63         1.236e+05  6.989e+03  17.692  < 2e-16 ***
Model_SeriesAMG GLA 35       1.586e+04  8.488e+03   1.868 0.066570 .
Model_SeriesAMG GLB 35       1.592e+04  8.484e+03   1.876 0.065383 .
Model_SeriesAMG GLC 43       2.285e+04  6.317e+03   3.617 0.000606 ***
Model_SeriesAMG GLE 43       3.401e+04  8.696e+03   3.911 0.000234 ***
Model_SeriesAMG GT 55        8.919e+04  8.865e+03  10.061 1.41e-14 ***
Model_SeriesAMG S 63         1.183e+05  8.512e+03  13.897  < 2e-16 ***
Model_SeriesAMG S 65         1.027e+05  8.905e+03  11.537  < 2e-16 ***
Model_SeriesAMG SLC 43       1.773e+04  8.805e+03   2.013 0.048497 *
Model_SeriesC-Class          6.961e+03  8.926e+03   0.780 0.438484
Model_SeriesCLA              3.593e+03  8.460e+03   0.425 0.672568
Model_SeriesCLE              2.478e+04  1.059e+04   2.339 0.022605 *
Model_SeriesCLK-Class        3.221e+04  1.063e+04   3.032 0.003568 **
Model_SeriesE-Class          2.450e+04  5.935e+03   4.128 0.000113 ***
Model_SeriesEQE              1.558e+04  8.872e+03   1.756 0.084038 .
Model_SeriesEQS              2.135e+04  9.205e+03   2.319 0.023748 *
Model_SeriesGL-Class         1.762e+04  8.951e+03   1.969 0.053516 .
Model_SeriesGLA              6.854e+03  5.475e+03   1.252 0.215394
Model_SeriesGLA-Class        2.156e+04  9.036e+03   2.386 0.020157 *
Model_SeriesGLB              6.669e+03  6.408e+03   1.041 0.302125
Model_SeriesGLC              6.933e+03  9.826e+03   0.706 0.483156
Model_SeriesGLE              2.412e+04  7.534e+03   3.202 0.002168 **
Model_SeriesGLK-Class        3.009e+04  7.432e+03   4.048 0.000148 ***
Model_SeriesGLS              3.788e+04  8.076e+03   4.691 1.58e-05 ***
Model_SeriesM-Class          2.604e+04  6.778e+03   3.842 0.000293 ***
Model_SeriesMetris           1.831e+04  7.222e+03   2.536 0.013800 *
Model_SeriesS-Class          3.793e+04  7.876e+03   4.816 1.01e-05 ***
Model_SeriesSprinter         2.161e+04  6.812e+03   3.172 0.002370 **
Model_SeriesUnknown          2.696e+04  8.245e+03   3.269 0.001774 **
Trim_LevelAMG G 63                  NA         NA      NA       NA
Trim_LevelAMG GT 55                 NA         NA      NA       NA
Trim_LevelBase                      NA         NA      NA       NA
Trim_LevelC 300              4.799e+03  7.959e+03   0.603 0.548755
Trim_LevelC 43                      NA         NA      NA       NA
Trim_LevelCLA 250                   NA         NA      NA       NA
Trim_LevelE 250              2.672e+04  8.656e+03   3.086 0.003045 **
Trim_LevelE 300             -9.467e+03  8.011e+03  -1.182 0.241888
Trim_LevelE 350             -2.390e+03  4.612e+03  -0.518 0.606191
Trim_LevelE 400             -2.984e+03  7.724e+03  -0.386 0.700638
Trim_LevelE 43                      NA         NA      NA       NA
Trim_LevelE 450              5.851e+03  5.501e+03   1.064 0.291699
Trim_LevelE 500                     NA         NA      NA       NA
Trim_LevelE 53                      NA         NA      NA       NA
Trim_LevelE 550             -1.372e+04  1.015e+04  -1.352 0.181446
Trim_LevelE 580              2.308e+04  8.720e+03   2.646 0.010334 *
Trim_LevelE 63               3.696e+04  7.557e+03   4.891 7.64e-06 ***
Trim_LevelGLA 250                   NA         NA      NA       NA
Trim_LevelGLA 35                    NA         NA      NA       NA
Trim_LevelGLB 250                   NA         NA      NA       NA
Trim_LevelGLB 35                    NA         NA      NA       NA
Trim_LevelGLK 350                   NA         NA      NA       NA
Trim_LevelS 450             -2.220e+03  6.044e+03  -0.367 0.714711
Trim_LevelS 550             -7.192e+03  7.322e+03  -0.982 0.329805
Trim_LevelS 580              1.155e+04  6.654e+03   1.736 0.087645 .
Trim_LevelS 63                      NA         NA      NA       NA
Trim_LevelS 65                      NA         NA      NA       NA
Trim_LevelStandard                  NA         NA      NA       NA
Body_TypeElectric SUV/Sedan         NA         NA      NA       NA
Body_TypeOther                      NA         NA      NA       NA
Body_TypeSedan                      NA         NA      NA       NA
Body_TypeSports/Roadster            NA         NA      NA       NA
Body_TypeSUV                        NA         NA      NA       NA
Body_TypeVan/Commercial             NA         NA      NA       NA
Is_4MATIC                   -8.028e+02  2.646e+03  -0.303 0.762650
Mileage_Miles               -3.218e-01  5.172e-02  -6.222 4.93e-08 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 6844 on 61 degrees of freedom
Multiple R-squared:  0.9661,	Adjusted R-squared:  0.9405
F-statistic: 37.74 on 46 and 61 DF,  p-value: < 2.2e-16